
version: 0.2

phases:
  install:
    commands:
      - echo Installing Nginx
      - set -e

      - echo 
      - sudo apt-get update || { echo "Failed to update package lists"; exit 1; }

      
      - sudo apt-get install -y nginx || { echo "Failed to install Nginx"; exit 1; }

      


  
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html/
  
  post_build:
    commands:
      - echo Configuring Nginx

artifacts:
  files:
    - /var/www/html/index.html
